### ISSUE TITLE
크롬에서 내려갔는데 무슨일임?

### ISSUE THREAD

**Issue by AfxousaAjagara** [CleanDC/CleanDC#18]
이제 더이상 배포안하기로한거? 갑자기 내려가있어서 놀랐네

**Comment by CleanDC** [comment]
크롬에서 정책이 바뀌어 권한마다 다 권한을 쓰는 이유를 명시해서 적어야 하고 검토를 받아야 하도록 바뀌어서 
건든거 없는데 내려갔습니다..
